export const ERROR_CODES = {
	BAD_REQUEST: 'BAD_REQUEST',
	VALIDATION_ERROR: 'VALIDATION_ERROR',
	STATE_CONFLICT: 'STATE_CONFLICT',
	NOT_FOUND: 'NOT_FOUND',
	UNAUTHORIZED_CUSTOMER: 'UNAUTHORIZED_CUSTOMER',
	INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
